# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38b7994d50367ea2d439bc4c19766c83c0850084b3f79d1253cb5bad9298fbd77415ccbbf6396d2b5b891d9bcceecd29336bf115104140c8b587c6522573a1f

test:
  secret_key_base: 9c0c00aecf24286550bc0b3ea1f6f388a0e81e72f563697e3f8afbf77c9018938bebaf1ea8784fbde502200b0c79f4dbe18f0f3757cabfb7c3a4f9f2e0c6311e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
